# Generated by Django 5.0 on 2024-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(max_length=40),
        ),
    ]
